name: disenn
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - pytorch
  - cpuonly
  - torchvision
  - tensorboard
  - scipy
  - pandas
  - scikit-learn
  - jupyter
  - kaggle